# Generated by Django 5.0.2 on 2024-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectcategory', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='static')),
            ],
        ),
    ]
