# Generated by Django 5.0.2 on 2024-04-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0002_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='photo',
        ),
    ]
