# Generated by Django 5.0.2 on 2024-04-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0003_remove_complaints_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static'),
        ),
    ]
