# Generated by Django 5.0.2 on 2024-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0004_complaints_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='complaint_photos'),
        ),
    ]
