# Generated by Django 5.0.2 on 2024-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0006_alter_complaints_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='photo',
            field=models.ImageField(default='', upload_to='complaint_photos/images'),
        ),
    ]
