# Generated by Django 5.0.2 on 2024-04-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvyApp', '0007_alter_complaints_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='photo',
        ),
    ]
